# Generated by Django 6.0.1 on 2026-02-24 23:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customerfield_customertag_customer_anniversary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('daily_rate', models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Daily Rate')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('quantity_total', models.PositiveIntegerField(default=1, verbose_name='Total Quantity')),
            ],
            options={
                'db_table': 'rentals_rentalitem',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RentalBlackout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='rentals.rentalitem')),
            ],
            options={
                'db_table': 'rentals_blackout',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('reference', models.CharField(max_length=50, verbose_name='Reference')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='reserved', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('total', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Total')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Deposit Amount')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='Deposit Paid')),
                ('deposit_returned', models.BooleanField(default=False, verbose_name='Deposit Returned')),
                ('condition_out', models.TextField(blank=True, verbose_name='Condition at Checkout')),
                ('condition_in', models.TextField(blank=True, verbose_name='Condition at Return')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.rentalitem')),
            ],
            options={
                'db_table': 'rentals_rental',
                'abstract': False,
            },
        ),
    ]
